language: generic
dist: trusty
env:
  HUGO_VERSION: "0.58.3"

cache:
  pip: true
  directories:
    - node_modules

install:
  - curl -sSL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o /tmp/hugo.tar.gz
  - tar -xzf /tmp/hugo.tar.gz -C $HOME/bin

script:
  - npm install
  - npm run lint:css
  - npm run lint:js
  - npm run production
  - hugo --minify --baseURL $BASE_URL

before_deploy:
  - pyenv global system 3.6
  - pip3 install --user awscli

deploy:
  provider: script
  script: aws s3 sync public s3://$S3_BUCKET_NAME --region $S3_BUCKET_REGION --acl public-read --delete
  skip_cleanup: true
  on:
    branch: master

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
