defaultContentLanguage: ro
defaultContentLanguageInSubdir: true
title: Code for Romania

languages:
  ro:
    languageName: Română
    languageCode: ro_RO
    copy: Organizație neguvernamentală independentă, neafiliată politic și apolitică.

  en:
    languageName: English
    languageCode: en_US
    copy: An independent, non-partisan, non-political, non-govermental organization.

permalinks:
  blog: /:section/:slug/

pygmentsCodeFences: true
pygmentsStyle: tango
enableEmoji: true
summaryLength: 20

staticDir:
  - static
  - theme

menu:
  social:
    - name: facebook
      url: https://www.facebook.com/code4romania/
      weight: 1
    - name: twitter
      url: https://twitter.com/Code4Romania
      weight: 2
    - name: github
      url: https://github.com/code4romania/
      weight: 3
    - name: linkedin
      url: https://www.linkedin.com/company/code4romania/
      weight: 4

params:
  sitemapExclude:
    - staff
    - programs

  appStatus:
    - id: covid
      icon: exclamation-triangle
    - id: done
      icon: check
    - id: development
      icon: wrench
    - id: incubation
      icon: exclamation-triangle
  
  # Must match exact button config on paypal
  paypal:
    buttonID:
      recurring: YED2GFGKUFXBJ
      onetime: C39VZYTTZGF82
    amounts: [ 5, 10, 20, 50, 100 ]

blackfriday:
  hrefTargetBlank: true
  fractions: false

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

googleAnalytics: UA-78737772-1
privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true

disableKinds:
  - taxonomy
  - taxonomyTerm
